var dt = [
    { eng: 'devtai karu dhyan deva tumache', hin: 'करु ध्यान देवा तुमचे', dir: 'dt', id: '1', bk: '', pg: '',  },
    { eng: 'devtai dharave na dhir dheer', hin: 'धरवेना धीर आता', dir: 'dt', id: '2', bk: '', pg: '',  },
    { eng: 'devtai sadguru yeshil ka', hin: 'सद्गुरु येशील का?', dir: 'dt', id: '2.2', bk: '', pg: '',  },
    { eng: 'devtai yega gururaya', hin: 'येगा गुरुराया', dir: 'dt', id: '3', bk: '', pg: '',  },
    { eng: 'devtai nana ale aale', hin: 'नाना आले ', dir: 'dt', id: '3.2', bk: '', pg: '',  },
    { eng: 'devtai karuya samayi suswagata', hin: 'करुया समयी सुस्वागता', dir: 'dt', id: '4', bk: '', pg: '',  },
    { eng: 'devtai acharani sadguruchya', hin: 'आचरणी सदगुरुच्या ', dir: 'dt', id: '5', bk: '', pg: '',  },
    { eng: 'devtai prapanchi din jan', hin: 'प्रपंची दीन जन आम्ही', dir: 'dt', id: '5.2', bk: '', pg: '',  },
    { eng: 'devtai kode ya mana', hin: 'कोडे या मना', dir: 'dt', id: '5.3', bk: '', pg: '',  },
    { eng: 'devtai ek guru ahe aahe', hin: 'एक गुरु आहे', dir: 'dt', id: '6', bk: '', pg: '',  },
    { eng: 'devtai deh karm bahya ho', hin: 'देह कर्म बाह्य हो', dir: 'dt', id: '6.2', bk: '', pg: '',  },
    { eng: 'devtai guru bhajanacha deva mala', hin: 'गुरु भजनाचा देवा मला', dir: 'dt', id: '7', bk: '', pg: '',  },
    { eng: 'devtai rini runi aho amhi tuze gururaya', hin: 'ऋणी आहो आम्ही तुझे गुरुराया', dir: 'dt', id: '7.2', bk: '', pg: '',  },
    { eng: 'devtai jo hanumanta palana', hin: 'जो जो हनुमंता (पाळणा)', dir: 'dt', id: '8', bk: '', pg: '',  },
    { eng: 'devtai anathacha nath amucha', hin: 'अनाथांचा नाथ अमुचा', dir: 'dt', id: '9', bk: '', pg: '',  },
    { eng: 'devtai ye javali bais aata', hin: 'ये जवळी बैस आता', dir: 'dt', id: '11', bk: '', pg: '',  },
    { eng: 'devtai tum prabhu ghat ke vasi', hin: 'तुम प्रभु घट घट के वासी', dir: 'dt', id: '11.2', bk: '', pg: '',  },
    { eng: 'devtai tumne tumane sikaya sikhaya', hin: 'मैं नही जाना था तुमने सिंकाया', dir: 'dt', id: '12', bk: '', pg: '',  },
    { eng: 'devtai bahut manaya pukara', hin: 'बहुत मनाया बहुत पुकारा ', dir: 'dt', id: '12.2', bk: '', pg: '',  },
    { eng: 'devtai ata paveto me tuze', hin: 'आता पावेतो मी तुझे', dir: 'dt', id: '13', bk: '', pg: '',  },
    { eng: 'devtai chaitramas padavyas gudi', hin: 'चैत्रमास पाडव्यास गुढी', dir: 'dt', id: '13.2', bk: '', pg: '',  },
    { eng: 'devtai dasnavami magh vadhyatali', hin: 'दासनवमी माघ वद्यातली', dir: 'dt', id: '14', bk: '', pg: '',  },
    { eng: 'devtai mandiri ram prabhu zulanar jhulanar palana', hin: 'मंदिरी राम प्रभु झुलणार (रामजन्म पाळणा)', dir: 'dt', id: '14.2', bk: '', pg: '',  },
    { eng: 'devtai darbar sadgurucha', hin: 'दरबार सद्गुरुचा', dir: 'dt', id: '15', bk: '', pg: '',  },
    { eng: 'devtai sadguru gharache varkari', hin: 'सद्गुरु घरचे वारकरी आम्ही', dir: 'dt', id: '15.2', bk: '', pg: '',  },
    { eng: 'devtai rit reet ho guruchi', hin: 'रीत हो गुरुची ऐसी', dir: 'dt', id: '16', bk: '', pg: '',  },
    { eng: 'devtai artmaniche sadguru amuche', hin: 'आर्तमनिचे सद्गुरु आमुचे', dir: 'dt', id: '17', bk: '', pg: '',  },
    { eng: 'devtai nardehache sar saar sadhuni', hin: 'नरदेहाचे सार साधुनी', dir: 'dt', id: '18', bk: '', pg: '',  },
    { eng: 'devtai panchtatva ki mail mel hai', hin: 'पंचतत्व की मेल है', dir: 'dt', id: '19', bk: '', pg: '',  },
    { eng: 'devtai prabhu bhaktichi vatchal', hin: 'प्रभु भक्तिची वाटचाल', dir: 'dt', id: '19.2', bk: '', pg: '',  },
    { eng: 'devtai guruche anand rup swarup', hin: 'गुरुचे आनंद रुप स्वरुप हे', dir: 'dt', id: '20', bk: '', pg: '',  },
    { eng: 'devtai mana nako duje kahi', hin: 'मना नको दुजे काही रे', dir: 'dt', id: '20.2', bk: '', pg: '',  },
    { eng: 'devtai kay kashi sangu guru leela lila', hin: 'काय कशी सांगु गुरु लीला', dir: 'dt', id: '21', bk: '', pg: '',  },
    { eng: 'devtai shravanat hindolyat', hin: 'श्रावणात हिंदोळ्यात', dir: 'dt', id: '22', bk: '', pg: '',  },
    { eng: 'devtai bhadrapad masi puja pooja ganeshasi', hin: 'भाद्रपद मासी पुजा गणेशासी', dir: 'dt', id: '22.2', bk: '', pg: '',  },
    { eng: 'devtai do din ke ye rajkaj', hin: 'दो दिनके ये राजकाज', dir: 'dt', id: '22.3', bk: '', pg: '',  },
    { eng: 'devtai mahima nahi jan jaan payi', hin: 'महिमा नही जान पायी', dir: 'dt', id: '23', bk: '', pg: '',  },
    { eng: 'devtai na jane kaise naiyako paar par lagana', hin: 'न जाने कैसी नैयाको पार लगाना', dir: 'dt', id: '23.2', bk: '', pg: '',  },
    { eng: 'devtai saguru tumachya ashramamadhye', hin: 'सद्गुरु तुमच्या आश्रमामध्ये', dir: 'dt', id: '24', bk: '', pg: '',  },
    { eng: 'devtai sant sangatine mana', hin: 'संत संगतीने मना', dir: 'dt', id: '25', bk: '', pg: '',  },
    { eng: 'devtai udaya ali ghyan kala', hin: 'उदया आली ज्ञान कला', dir: 'dt', id: '26', bk: '', pg: '',  },
    { eng: 'devtai pindi je tech bramhandi', hin: 'पिंडी जे तेच ब्रह्मांडी', dir: 'dt', id: '26.2', bk: '', pg: '',  },
    { eng: 'devtai bhakticha bodh bij beej', hin: 'भक्तिचा बोध बीज', dir: 'dt', id: '27', bk: '', pg: '',  },
    { eng: 'devtai guru gun gaan mana', hin: 'गुरु गुण गान गा मना', dir: 'dt', id: '28', bk: '', pg: '',  },
    { eng: 'devtai jag prabho', hin: 'जाग जाग जाग प्रभो ', dir: 'dt', id: '28.2', bk: '', pg: '',  },
    { eng: 'devtai kon me ghyan bodhe', hin: 'कोण मी ज्ञान बोधे', dir: 'dt', id: '28.3', bk: '', pg: '',  },
    { eng: 'devtai maya mohase bach manava', hin: 'माया मोहसे बच जा रे मनवा', dir: 'dt', id: '29', bk: '', pg: '',  },
    { eng: 'devtai datta janmotsavachi ghadi', hin: 'दत्त जन्मोत्सवाची घडी येतसे', dir: 'dt', id: '30', bk: '', pg: '',  },
    { eng: 'devtai prarthi yashoda nach manmohana', hin: 'प्रार्थी यशोदा नाच नाच मनमोहना', dir: 'dt', id: '30.2', bk: '', pg: '',  },
    { eng: 'devtai tilgud utsav god kara', hin: 'तिळगुळ उत्सव गोड करा', dir: 'dt', id: '32', bk: '', pg: '',  },
    { eng: 'devtai jayadeva sadguru ghyanrupa', hin: 'जयदेवा सद्गुरु (आरती)', dir: 'dt', id: '32.2', bk: '', pg: '',  },
    { eng: 'devtai vandu guruchya charanar vinda', hin: 'वंदु गुरुच्या चरणार विंदा', dir: 'dt', id: '33', bk: '', pg: '',  },
    { eng: 'devtai ata kadhi yenar tav bheticha', hin: 'आता कधी येणार तव भेटीचा', dir: 'dt', id: '34', bk: '', pg: '',  },
    { eng: 'devtai sadguru prasanna', hin: 'श्री सद्गुरु प्रसन्न ', dir: 'dt', id: '35', bk: '', pg: '',  },
    { eng: 'devtai aas ekachi ekchi dharali', hin: 'आस एकची ही धरली', dir: 'dt', id: '35.2', bk: '', pg: '',  },
    { eng: 'devtai tuchi ata marg davi', hin: 'तुची आता मज मार्ग दावी', dir: 'dt', id: '36', bk: '', pg: '',  }

];

if (typeof module === 'object' && module.exports) {
    module.exports = dt;
}
