var mv = [
  
	{ eng: 'martand vaibhav maz vari krupa kari', hin: 'श्री मार्तंड वैभव - मजवरी कृपा करी', dir: 'mv', id: '1', bk: '', pg: ''},
	{ eng: 'martand vaibhav prabhat smaran bhupali', hin: 'श्री मार्तंड वैभव - प्रभात स्मरण (भूपाळी)', dir: 'mv', id: '2', bk: '', pg: ''},
	{ eng: 'martand vaibhav nana suprabhatam', hin: 'श्री मार्तंड वैभव - नाना सुप्रभातम्', dir: 'mv', id: '3', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '4', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '5', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '6', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '7', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '8', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '9', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '8', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '9', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '10', bk: '', pg: ''},	
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '11', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '12', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '13', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '14', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '15', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '16', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '17', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '18', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '19', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '18', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '19', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '10', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '21', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '22', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '23', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '24', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '25', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '26', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '27', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '28', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '29', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '28', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '29', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '20', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '30', bk: '', pg: ''},	
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '31', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '32', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '33', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '34', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '35', bk: '', pg: ''},
	//{ eng: 'martand vaibhav ', hin: 'श्री मार्तंड वैभव - ', dir: 'mv', id: '36', bk: '', pg: ''},
 
];

if (typeof module === 'object' && module.exports) {
    module.exports = mv;
}
