var ntn = [
        { eng: 'kakad arati bhupali', hin: 'काकड आरती-भूपाळी', dir: 'ntn', id: '6.1', bk: 'नाना तिरीचा नामरंग', pg: '6' },
        { eng: 'kakad arati shri datta prabodh stav', hin: 'काकड आरती-श्री दत्त प्रभोधस्तव' , dir: 'ntn', id: '6.2' , bk: 'नाना तिरीचा नामरंग', pg: '6' },
        { eng: 'kakad arati aarati arti jay deva shri sadguru dnyan', hin: 'काकड आरती-जय देवा श्री सद्गुरु जय ज्ञान रुपा',  dir: 'ntn', id: '8' , bk: 'नाना तिरीचा नामरंग', pg: '8' },
        { eng: 'kakad arati shri dattatreya prarthan chashk', hin: 'काकड आरती-श्री दत्तात्रेय प्रार्थना चतुष्क', dir: 'ntn', id: '9', bk: 'नाना तिरीचा नामरंग', pg: '9' },
        { eng: 'kakad arati manas atm puja pooja', hin: 'काकड आरती-श्री मानस पूजा (श्री आत्मपूजा)', dir: 'ntn', id: '10', bk: 'नाना तिरीचा नामरंग', pg: '10' }, 
        { eng: 'prabhati jago mohan pyare', hin: 'प्रभाती-जागो मोहन प्यारे', dir: 'ntn', id: '13', bk: 'नाना तिरीचा नामरंग', pg: '13' }, 
        { eng: 'prabhati jagiye raghunath kunvar kuvar', hin: 'प्रभाती-जागिये रघुनाथ कुँवर', dir: 'ntn', id: '13.2', bk: 'नाना तिरीचा नामरंग', pg: '13' }, 
        { eng: 'prabhati uth pandharichya raya', hin: 'प्रभाती-उठ पंढरीच्या राया', dir: 'ntn', id: '14', bk: 'नाना तिरीचा नामरंग', pg: '14' }, 
        { eng: 'prabhati uthi ba shri guruvara', hin: 'प्रभाती-उठी उठी बा श्री गुरुवरा मार्तंडा', dir: 'ntn', id: '14.2', bk: 'नाना तिरीचा नामरंग', pg: '14' }, 
        { eng: 'prabhati guruji me main to ek', hin: 'प्रभाती-गुरुजी मै तो एक निरंजन', dir: 'ntn', id: '15', bk: 'नाना तिरीचा नामरंग', pg: '15' }, 
        { eng: 'prabhati bheti lage maze', hin: 'प्रभाती-भेटी लागी माझे', dir: 'ntn', id: '16', bk: 'नाना तिरीचा नामरंग', pg: '16' }, 
        { eng: 'prabhati jag prabho', hin: 'प्रभाती-जाग जाग जाग प्रभो', dir: 'ntn', id: '16.2', bk: 'नाना तिरीचा नामरंग', pg: '16' }, 
        { eng: 'aukshan karuya samayi suswagata', hin: 'करुया समयी सुस्वागता', dir: 'ntn', id: '18', bk: 'नाना तिरीचा नामरंग', pg: '18' }, 
        { eng: 'acharani sadgurucha', hin: 'आचरणी सद्गुरुच्या', dir: 'ntn', id: '18.2', bk: 'नाना तिरीचा नामरंग', pg: '18' }, 
        { eng: 'prapanchi din deen jan aamhi', hin: 'प्रपंची दीन जन आम्ही', dir: 'ntn', id: '19', bk: 'नाना तिरीचा नामरंग', pg: '19' }, 
        { eng: 'kode ya mana', hin: 'कोडे या मना', dir: 'ntn', id: '19.2', bk: 'नाना तिरीचा नामरंग', pg: '19' },         
        { eng: 'nana aale ale', hin: 'नाना आले नाना आले', dir: 'ntn', id: '20', bk: 'नाना तिरीचा नामरंग', pg: '20' }, 
        { eng: 'ek guru ahe aahe', hin: 'एक गुरु आहे', dir: 'ntn', id: '20.2', bk: 'नाना तिरीचा नामरंग', pg: '20' }, 
        { eng: 'deh karm bahy ho', hin: 'देह कर्म बाह्य हो', dir: 'ntn', id: '21', bk: 'नाना तिरीचा नामरंग', pg: '21' },  
        { eng: 'guru bhajanacha deva mala rang lago', hin: 'गुरु भजनाचा देवा मला रंग लागो', dir: 'ntn', id: '21.2', bk: 'नाना तिरीचा नामरंग', pg: '21' },  
        { eng: 'alankapuri punya bhumi pavitra', hin: 'अलंकापुरी पुण्य भुमी पवित्र', dir: 'ntn', id: '23', bk: 'नाना तिरीचा नामरंग', pg: '23' }, 
        { eng: 'rup pahata lochani', hin: 'रुप पाहता लोचनी', dir: 'ntn', id: '23.2', bk: 'नाना तिरीचा नामरंग', pg: '23' }, 
        { eng: 'sadguru yave yaave', hin: 'सद्गुरु यावे', dir: 'ntn', id: '24', bk: 'नाना तिरीचा नामरंग', pg: '24' }, 
        { eng: 'bhimatiri ek basavile nagar', hin: 'भीमातीरी एक बसविले नगर', dir: 'ntn', id: '25', bk: 'नाना तिरीचा नामरंग', pg: '25' }, 
        { eng: 'manuja ram bhajava', hin: 'मनुजा राम भजावा रे ', dir: 'ntn', id: '26', bk: 'नाना तिरीचा नामरंग', pg: '26' }, 
        { eng: 'lagala chataka', hin: 'लागला चटका', dir: 'ntn', id: '26.2', bk: 'नाना तिरीचा नामरंग', pg: '26' }, 
        { eng: 'ekade basavili pandhari', hin: 'इकडे बसविली पंढरी', dir: 'ntn', id: '27', bk: 'नाना तिरीचा नामरंग', pg: '27' }, 
        { eng: 'kuni nahi kunacha sakha', hin: 'कुणी नाही कुणाचा सखा', dir: 'ntn', id: '28', bk: 'नाना तिरीचा नामरंग', pg: '28' }, 
        { eng: 'hanumant mahabali', hin: 'हनुमंत महाबळी', dir: 'ntn', id: '29', bk: 'नाना तिरीचा नामरंग', pg: '29' }, 
        { eng: 'pandurang shrirang bhajare mana', hin: 'पांडुरंग श्रीरंग, भजरे मना', dir: 'ntn', id: '29.2', bk: 'नाना तिरीचा नामरंग', pg: '29' }, 
        { eng: 'bhaj nara satat', hin: 'भज नरा सतत', dir: 'ntn', id: '30', bk: 'नाना तिरीचा नामरंग', pg: '30' },          
        { eng: 'ek don tin char', hin: 'एक दोन तीन चार', dir: 'ntn', id: '30.2', bk: 'नाना तिरीचा नामरंग', pg: '30' },          
        { eng: 'kshir sagarichya pundya', hin: 'क्षीर सागरीच्या पुण्ड्या', dir: 'ntn', id: '31', bk: 'नाना तिरीचा नामरंग', pg: '31' },          
        { eng: 'adhi hota vaghya', hin: 'आधी होता वाघ्या', dir: 'ntn', id: '31.2', bk: 'नाना तिरीचा नामरंग', pg: '31' },          
        { eng: 'bramhan to ek narahari sonar', hin: 'ब्राह्मण तो एक नरहरि सोनार', dir: 'ntn', id: '32', bk: 'नाना तिरीचा नामरंग', pg: '32' },          
        { eng: 'kanhobachi sangati', hin: 'कान्होबाची संगती', dir: 'ntn', id: '33', bk: 'नाना तिरीचा नामरंग', pg: '33' },          
        { eng: 'nachat jau tychya gava re kheliya', hin: 'नाचत जाऊ त्याच्या गावा रे खेळिया', dir: 'ntn', id: '33.2', bk: 'नाना तिरीचा नामरंग', pg: '33' },          
        { eng: 'hari tuzya muralit kay re', hin: 'हरी तुझ्या मुरलीत काय रे', dir: 'ntn', id: '34', bk: 'नाना तिरीचा नामरंग', pg: '34' },
        { eng: 'to nar nataka', hin: 'तो नर नर नटका', dir: 'ntn', id: '34.2', bk: 'नाना तिरीचा नामरंग', pg: '34' },
        { eng: 'hari nam hardam mat bhulo', hin: 'हरी नाम हरदम मत भूलो', dir: 'ntn', id: '35', bk: 'नाना तिरीचा नामरंग', pg: '35' },
        { eng: 'jag jahan chale ufrat ufarat', hin: 'जग जहान चले उफराट', dir: 'ntn', id: '36', bk: 'नाना तिरीचा नामरंग', pg: '36' },
        { eng: 'bhala kare peer murshad maula mola', hin: 'भला करे पीर मुर्शद मौला', dir: 'ntn', id: '36.2', bk: 'नाना तिरीचा नामरंग', pg: '36' },
        { eng: 'baje damaru shiv shankar', hin: 'बाजे डमरु शिवशंकर का', dir: 'ntn', id: '37', bk: 'नाना तिरीचा नामरंग', pg: '37' },
        { eng: 'ek din jana re bhai', hin: 'एक दिन जाना रे भाई', dir: 'ntn', id: '38', bk: 'नाना तिरीचा नामरंग', pg: '38' },
        { eng: 'datta nam nahi gavega', hin: 'दत्त नाम नहीं गावेगा', dir: 'ntn', id: '38.2', bk: 'नाना तिरीचा नामरंग', pg: '38' },
        { eng: 'bhai nirakar nirgun ke desh', hin: 'भाई निराकार निर्गुण के देश में रहेना', dir: 'ntn', id: '39', bk: 'नाना तिरीचा नामरंग', pg: '39' },
        { eng: 'satgurune mauj dikhai', hin: 'सत् गुरुने मौज दिखाई', dir: 'ntn', id: '40', bk: 'नाना तिरीचा नामरंग', pg: '40' },
        { eng: 'manava bhul mat jaiyyo', hin: 'मनवा भूलो मत जईय्यो', dir: 'ntn', id: '40.2', bk: 'नाना तिरीचा नामरंग', pg: '40' },
        { eng: 'shri guru sarikha asata pathirakha', hin: 'श्री गुरुसारिखा असता पाठीराखा ', dir: 'ntn', id: '43', bk: 'नाना तिरीचा नामरंग', pg: '43' },
        { eng: 'barich vit jadalis pundalika', hin: 'बरीच वीट जडलीस रे पुंडलिका', dir: 'ntn', id: '43.2', bk: 'नाना तिरीचा नामरंग', pg: '43' },
        { eng: 'shriguru datta muni', hin: 'श्रीगुरु दत्तमुनी ', dir: 'ntn', id: '44', bk: 'नाना तिरीचा नामरंग', pg: '44' },
        { eng: 'janma yeuni marashi', hin: 'जन्मा येवूनी का मरशी', dir: 'ntn', id: '44.2', bk: 'नाना तिरीचा नामरंग', pg: '44' },
        { eng: 'adhi punya karu', hin: 'आधी पुण्य करु', dir: 'ntn', id: '45', bk: 'नाना तिरीचा नामरंग', pg: '45' },
        { eng: 'punyavant vhave', hin: 'पुण्यवंत व्हावे', dir: 'ntn', id: '45.2', bk: 'नाना तिरीचा नामरंग', pg: '45' },
        { eng: 'nahi santpan milate hati', hin: 'नाही संतपण मिळते ते हाटी', dir: 'ntn', id: '46', bk: 'नाना तिरीचा नामरंग', pg: '46' },
        { eng: 'asi dhari chhand', hin: 'असी धरी छंद', dir: 'ntn', id: '46.2', bk: 'नाना तिरीचा नामरंग', pg: '46' },
        { eng: 'sada santapashi jave', hin: 'सदा संतांपाशी जावे', dir: 'ntn', id: '47', bk: 'नाना तिरीचा नामरंग', pg: '47' },
        { eng: 'hari smaran vismaran', hin: 'हरी स्मरण विस्मरण', dir: 'ntn', id: '47.2', bk: 'नाना तिरीचा नामरंग', pg: '47' },
        { eng: 'trushna trishna ko dhire nikal', hin: 'तृष्णा को धिरे निकाल', dir: 'ntn', id: '48', bk: 'नाना तिरीचा नामरंग', pg: '48' },
        { eng: 'ghu ghunguru ghunghuru bajay', hin: 'घुं घुं घुंघरू बजाय गई हो', dir: 'ntn', id: '49', bk: 'नाना तिरीचा नामरंग', pg: '49' },
        { eng: 'mandir me kyo kyu sir marati dole', hin: 'मंदीर में क्यो सिर मारती डोले', dir: 'ntn', id: '49.2', bk: 'नाना तिरीचा नामरंग', pg: '49' },
        { eng: 'tin shire saha hath', hin: 'तिन शिरे सहा हात ', dir: 'ntn', id: '51', bk: 'नाना तिरीचा नामरंग', pg: '51' },
        { eng: 'naman maze gururaya', hin: 'नमन माझे गुरुराया', dir: 'ntn', id: '51.2', bk: 'नाना तिरीचा नामरंग', pg: '51' },
        { eng: 'ata kothe dhave mana', hin: 'आता कोठे धावे मना', dir: 'ntn', id: '52', bk: 'नाना तिरीचा नामरंग', pg: '52' },
        { eng: 'avade he rup gojire sagun', hin: 'आवडे हे रुप गोजिरे सगुण', dir: 'ntn', id: '52.2', bk: 'नाना तिरीचा नामरंग', pg: '52' },
        { eng: 'rupi guntale lochan', hin: 'रुपी गुंतले लोचन', dir: 'ntn', id: '52.3', bk: 'नाना तिरीचा नामरंग', pg: '52' },
        { eng: 'sada maze dola', hin: 'सदा माझे डोळा', dir: 'ntn', id: '53', bk: 'नाना तिरीचा नामरंग', pg: '53' },
        { eng: 'sadguru vachoni sapadena soy', hin: 'सद्‌गुरु वाचोनी सापडेना सोय', dir: 'ntn', id: '53.2', bk: 'नाना तिरीचा नामरंग', pg: '53' },
        { eng: 'namo adirupa', hin: 'नमो आदीरुपा', dir: 'ntn', id: '55', bk: 'नाना तिरीचा नामरंग', pg: '55' },
        { eng: 'avade he rup', hin: 'आवडे हे रुप', dir: 'ntn', id: '55.3', bk: 'नाना तिरीचा नामरंग', pg: '55' },
        { eng: 'sundar te dhyan', hin: 'सुंदर ते ध्यान', dir: 'ntn', id: '56.2', bk: 'नाना तिरीचा नामरंग', pg: '56' },
        { eng: 'dev maza vithu savala', hin: 'देव माझा विठू सावळा', dir: 'ntn', id: '57', bk: 'नाना तिरीचा नामरंग', pg: '57' },
        { eng: 'namila ganapati mauli sharada', hin: 'नमिला गणपती माऊली शारदा', dir: 'ntn', id: '57.2', bk: 'नाना तिरीचा नामरंग', pg: '57' },
        { eng: 'ghyaniyancha raja', hin: 'ज्ञानियांचा राजा', dir: 'ntn', id: '58', bk: 'नाना तिरीचा नामरंग', pg: '58' },
        { eng: 'jayachiye dvari sonyacha pimpal', hin: 'जयाचिये व्दारी; सोन्याचा पिंपळ ', dir: 'ntn', id: '58.2', bk: 'नाना तिरीचा नामरंग', pg: '58' },
        { eng: 'indrayani kathi', hin: 'इंद्रायणी काठी', dir: 'ntn', id: '58.3', bk: 'नाना तिरीचा नामरंग', pg: '58' },
        { eng: 'guru maza moksha data', hin: 'गुरु माझा मोक्ष दाता ', dir: 'ntn', id: '59', bk: 'नाना तिरीचा नामरंग', pg: '59' },
        { eng: 'avadine bhave harinam ghesi', hin: 'आवडीने भावे हरीनाम घेसी', dir: 'ntn', id: '60.2', bk: 'नाना तिरीचा नामरंग', pg: '60' },
        { eng: 'amrutahuni god nam', hin: 'अमृताहुनी गोड नाम', dir: 'ntn', id: '60.3', bk: 'नाना तिरीचा नामरंग', pg: '60' },
        { eng: 'kare ushir laviyela', hin: 'कारे उशीर लावियेला', dir: 'ntn', id: '65.3', bk: 'नाना तिरीचा नामरंग', pg: '65' },
        { eng: 'thevile anante taisechi rahave', hin: 'ठेविले अनंते तैसेचि रहावे ', dir: 'ntn', id: '66.3', bk: 'नाना तिरीचा नामरंग', pg: '66' },
        { eng: 'devpuja mazi', hin: 'देवपूजा मांझी देवपूजा', dir: 'ntn', id: '69.2', bk: 'नाना तिरीचा नामरंग', pg: '69' },
        { eng: 'kanhopatra dasi bole', hin: 'कान्होपात्रा दासी बोले', dir: 'ntn', id: '70.2', bk: 'नाना तिरीचा नामरंग', pg: '70' },
        { eng: 'he adima he antima', hin: 'हे आदिमा हे अंतिमा', dir: 'ntn', id: '71.2', bk: 'नाना तिरीचा नामरंग', pg: '71' },
        { eng: 'abir gulal udhalit rang', hin: 'अबीर गुलाल उधळीत रंग', dir: 'ntn', id: '72.2', bk: 'नाना तिरीचा नामरंग', pg: '72' },
        { eng: 'deva tuza me sonar', hin: 'देवा तुझा मी सोनार ', dir: 'ntn', id: '73.2', bk: 'नाना तिरीचा नामरंग', pg: '73' },
        { eng: 'anandacha kand guru ha', hin: 'आनंदा कंद गुरु हा', dir: 'ntn', id: '73.3', bk: 'नाना तिरीचा नामरंग', pg: '73' },
        { eng: 'krushnatirichya vasanarya', hin: 'कृष्णातिरीच्या वसणाऱ्या', dir: 'ntn', id: '74', bk: 'नाना तिरीचा नामरंग', pg: '74' },
        { eng: 'sangave kavanya thaya jave', hin: 'सांगावे, कवण्या ठाया जावे?', dir: 'ntn', id: '74.2', bk: 'नाना तिरीचा नामरंग', pg: '74' },
             { eng: 'magane he ek tuzprati ahe', hin: 'मागणे हे एक तुजप्रती आहे', dir: 'ntn', id: '124', bk: 'नाना तिरीचा नामरंग', pg: '124' },


    ];

if (typeof module === 'object' && module.exports) {
    module.exports = ntn;
}
