var ntn = [
        { eng: 'kakad arati bhupali', hin: 'काकड आरती-भूपाळी', dir: 'ntn', id: '6.1', bk: 'नाना तिरीचा नामरंग', pg: '6' },
        { eng: 'kakad arati shri datta prabodh stav', hin: 'काकड आरती-श्री दत्त प्रभोधस्तव' , dir: 'ntn', id: '6.2' , bk: 'नाना तिरीचा नामरंग', pg: '6' },
        { eng: 'kakad arati aarati arti jay deva shri sadguru dnyan', hin: 'काकड आरती-जय देवा श्री सद्गुरु जय ज्ञान रुपा',  dir: 'ntn', id: '8' , bk: 'नाना तिरीचा नामरंग', pg: '8' },
        { eng: 'kakad arati shri dattatreya prarthan chashk', hin: 'काकड आरती-श्री दत्तात्रेय प्रार्थना चतुष्क', dir: 'ntn', id: '9', bk: 'नाना तिरीचा नामरंग', pg: '9' },
        { eng: 'kakad arati manas atm puja pooja', hin: 'काकड आरती-श्री मानस पूजा (श्री आत्मपूजा)', dir: 'ntn', id: '10', bk: 'नाना तिरीचा नामरंग', pg: '10' }, 
        { eng: 'prabhati jago mohan pyare', hin: 'प्रभाती-जागो मोहन प्यारे', dir: 'ntn', id: '13', bk: 'नाना तिरीचा नामरंग', pg: '13' }, 
        { eng: 'prabhati jagiye raghunath kunvar kuvar', hin: 'प्रभाती-जागिये रघुनाथ कुँवर', dir: 'ntn', id: '13.2', bk: 'नाना तिरीचा नामरंग', pg: '13' }, 
        { eng: 'prabhati uth pandharichya raya', hin: 'प्रभाती-उठ पंढरीच्या राया', dir: 'ntn', id: '14', bk: 'नाना तिरीचा नामरंग', pg: '14' }, 
        { eng: 'prabhati uthi ba shri guruvara', hin: 'प्रभाती-उठी उठी बा श्री गुरुवरा मार्तंडा', dir: 'ntn', id: '14.2', bk: 'नाना तिरीचा नामरंग', pg: '14' }, 
        { eng: 'prabhati guruji me main to ek', hin: 'प्रभाती-गुरुजी मै तो एक निरंजन', dir: 'ntn', id: '15', bk: 'नाना तिरीचा नामरंग', pg: '15' }, 
        { eng: 'prabhati bheti lage maze', hin: 'प्रभाती-भेटी लागी माझे', dir: 'ntn', id: '16', bk: 'नाना तिरीचा नामरंग', pg: '16' }, 
        { eng: 'prabhati jag prabho', hin: 'प्रभाती-जाग जाग जाग प्रभो', dir: 'ntn', id: '16.2', bk: 'नाना तिरीचा नामरंग', pg: '16' }, 
        { eng: 'aukshan karuya samayi suswagata', hin: 'करुया समयी सुस्वागता', dir: 'ntn', id: '18', bk: 'नाना तिरीचा नामरंग', pg: '18' }, 
        { eng: 'acharani sadgurucha', hin: 'आचरणी सद्गुरुच्या', dir: 'ntn', id: '18.2', bk: 'नाना तिरीचा नामरंग', pg: '18' }, 
        { eng: 'prapanchi din deen jan aamhi', hin: 'प्रपंची दीन जन आम्ही', dir: 'ntn', id: '19', bk: 'नाना तिरीचा नामरंग', pg: '19' }, 
        { eng: 'kode ya mana', hin: 'कोडे या मना', dir: 'ntn', id: '19.2', bk: 'नाना तिरीचा नामरंग', pg: '19' },         
        { eng: 'nana aale ale', hin: 'नाना आले नाना आले', dir: 'ntn', id: '20', bk: 'नाना तिरीचा नामरंग', pg: '20' }, 
        { eng: 'ek guru ahe aahe', hin: 'एक गुरु आहे', dir: 'ntn', id: '20.2', bk: 'नाना तिरीचा नामरंग', pg: '20' }, 
        { eng: 'deh karm bahy ho', hin: 'देह कर्म बाह्य हो', dir: 'ntn', id: '21', bk: 'नाना तिरीचा नामरंग', pg: '21' },  
        { eng: 'guru bhajanacha deva mala rang lago', hin: 'गुरु भजनाचा देवा मला रंग लागो', dir: 'ntn', id: '21.2', bk: 'नाना तिरीचा नामरंग', pg: '21' },  
        { eng: 'alankapuri punya bhumi pavitra', hin: 'अलंकापुरी पुण्य भुमी पवित्र', dir: 'ntn', id: '23', bk: 'नाना तिरीचा नामरंग', pg: '23' }, 
        { eng: 'rup pahata lochani', hin: 'रुप पाहता लोचनी', dir: 'ntn', id: '23.2', bk: 'नाना तिरीचा नामरंग', pg: '23' }, 
        { eng: 'sadguru yave yaave', hin: 'सद्गुरु यावे', dir: 'ntn', id: '24', bk: 'नाना तिरीचा नामरंग', pg: '24' }, 
        { eng: 'bhimatiri ek basavile nagar', hin: 'भीमातीरी एक बसविले नगर', dir: 'ntn', id: '25', bk: 'नाना तिरीचा नामरंग', pg: '25' }, 
        { eng: 'manuja ram bhajava', hin: 'मनुजा राम भजावा रे ', dir: 'ntn', id: '26', bk: 'नाना तिरीचा नामरंग', pg: '26' }, 
        { eng: 'lagala chataka', hin: 'लागला चटका', dir: 'ntn', id: '26.2', bk: 'नाना तिरीचा नामरंग', pg: '26' }, 
        { eng: 'ekade basavili pandhari', hin: 'इकडे बसविली पंढरी', dir: 'ntn', id: '27', bk: 'नाना तिरीचा नामरंग', pg: '27' }, 
        { eng: 'kuni nahi kunacha sakha', hin: 'कुणी नाही कुणाचा सखा', dir: 'ntn', id: '28', bk: 'नाना तिरीचा नामरंग', pg: '28' }, 
        { eng: 'hanumant mahabali', hin: 'हनुमंत महाबळी', dir: 'ntn', id: '29', bk: 'नाना तिरीचा नामरंग', pg: '29' }, 
        { eng: 'pandurang shrirang bhajare mana', hin: 'पांडुरंग श्रीरंग, भजरे मना', dir: 'ntn', id: '29.2', bk: 'नाना तिरीचा नामरंग', pg: '29' }, 
        { eng: 'bhaj nara satat', hin: 'भज नरा सतत', dir: 'ntn', id: '30', bk: 'नाना तिरीचा नामरंग', pg: '30' },          
        { eng: 'ek don tin char', hin: 'एक दोन तीन चार', dir: 'ntn', id: '30.2', bk: 'नाना तिरीचा नामरंग', pg: '30' },          
        { eng: 'kshir sagarichya pundya', hin: 'क्षीर सागरीच्या पुण्ड्या', dir: 'ntn', id: '31', bk: 'नाना तिरीचा नामरंग', pg: '31' },          
        { eng: 'adhi hota vaghya', hin: 'आधी होता वाघ्या', dir: 'ntn', id: '31.2', bk: 'नाना तिरीचा नामरंग', pg: '31' },          
        { eng: 'bramhan to ek narahari sonar', hin: 'ब्राह्मण तो एक नरहरि सोनार', dir: 'ntn', id: '32', bk: 'नाना तिरीचा नामरंग', pg: '32' },          
        { eng: 'kanhobachi sangati', hin: 'कान्होबाची संगती', dir: 'ntn', id: '33', bk: 'नाना तिरीचा नामरंग', pg: '33' },          
        { eng: 'nachat jau tychya gava re kheliya', hin: 'नाचत जाऊ त्याच्या गावा रे खेळिया', dir: 'ntn', id: '33.2', bk: 'नाना तिरीचा नामरंग', pg: '33' },          
        { eng: 'hari tuzya muralit kay re', hin: 'हरी तुझ्या मुरलीत काय रे', dir: 'ntn', id: '34', bk: 'नाना तिरीचा नामरंग', pg: '34' },
        { eng: 'to nar nataka', hin: 'तो नर नर नटका', dir: 'ntn', id: '34.2', bk: 'नाना तिरीचा नामरंग', pg: '34' },
        { eng: 'hari nam hardam mat bhulo', hin: 'हरी नाम हरदम मत भूलो', dir: 'ntn', id: '35', bk: 'नाना तिरीचा नामरंग', pg: '35' },
        { eng: 'jag jahan chale ufrat ufarat', hin: 'जग जहान चले उफराट', dir: 'ntn', id: '36', bk: 'नाना तिरीचा नामरंग', pg: '36' },
        { eng: 'bhala kare peer murshad maula mola', hin: 'भला करे पीर मुर्शद मौला', dir: 'ntn', id: '36.2', bk: 'नाना तिरीचा नामरंग', pg: '36' },
        { eng: 'baje damaru shiv shankar', hin: 'बाजे डमरु शिवशंकर का', dir: 'ntn', id: '37', bk: 'नाना तिरीचा नामरंग', pg: '37' },
        { eng: 'ek din jana re bhai', hin: 'एक दिन जाना रे भाई', dir: 'ntn', id: '38', bk: 'नाना तिरीचा नामरंग', pg: '38' },
        { eng: 'datta nam nahi gavega', hin: 'दत्त नाम नहीं गावेगा', dir: 'ntn', id: '38.2', bk: 'नाना तिरीचा नामरंग', pg: '38' },
        { eng: 'bhai nirakar nirgun ke desh', hin: 'भाई निराकार निर्गुण के देश में रहेना', dir: 'ntn', id: '39', bk: 'नाना तिरीचा नामरंग', pg: '39' },
        { eng: 'satgurune mauj dikhai', hin: 'सत् गुरुने मौज दिखाई', dir: 'ntn', id: '40', bk: 'नाना तिरीचा नामरंग', pg: '40' },
        { eng: 'manava bhul mat jaiyyo', hin: 'मनवा भूलो मत जईय्यो', dir: 'ntn', id: '40.2', bk: 'नाना तिरीचा नामरंग', pg: '40' },
        { eng: 'shri guru sarikha asata pathirakha', hin: 'श्री गुरुसारिखा असता पाठीराखा ', dir: 'ntn', id: '43', bk: 'नाना तिरीचा नामरंग', pg: '43' },
        { eng: 'barich vit jadalis pundalika', hin: 'बरीच वीट जडलीस रे पुंडलिका', dir: 'ntn', id: '43.2', bk: 'नाना तिरीचा नामरंग', pg: '43' },
        { eng: 'shriguru datta muni', hin: 'श्रीगुरु दत्तमुनी ', dir: 'ntn', id: '44', bk: 'नाना तिरीचा नामरंग', pg: '44' },
        { eng: 'janma yeuni marashi', hin: 'जन्मा येवूनी का मरशी', dir: 'ntn', id: '44.2', bk: 'नाना तिरीचा नामरंग', pg: '44' },
        { eng: 'adhi punya karu', hin: 'आधी पुण्य करु', dir: 'ntn', id: '45', bk: 'नाना तिरीचा नामरंग', pg: '45' },
        { eng: 'punyavant vhave', hin: 'पुण्यवंत व्हावे', dir: 'ntn', id: '45.2', bk: 'नाना तिरीचा नामरंग', pg: '45' },
        { eng: 'nahi santpan milate hati', hin: 'नाही संतपण मिळते ते हाटी', dir: 'ntn', id: '46', bk: 'नाना तिरीचा नामरंग', pg: '46' },
        { eng: 'asi dhari chhand', hin: 'असी धरी छंद', dir: 'ntn', id: '46.2', bk: 'नाना तिरीचा नामरंग', pg: '46' },
        { eng: 'sada santapashi jave', hin: 'सदा संतांपाशी जावे', dir: 'ntn', id: '47', bk: 'नाना तिरीचा नामरंग', pg: '47' },
        { eng: 'hari smaran vismaran', hin: 'हरी स्मरण विस्मरण', dir: 'ntn', id: '47.2', bk: 'नाना तिरीचा नामरंग', pg: '47' },
        { eng: 'trushna trishna ko dhire nikal', hin: 'तृष्णा को धिरे निकाल', dir: 'ntn', id: '48', bk: 'नाना तिरीचा नामरंग', pg: '48' },
        { eng: 'ghu ghunguru ghunghuru bajay', hin: 'घुं घुं घुंघरू बजाय गई हो', dir: 'ntn', id: '49', bk: 'नाना तिरीचा नामरंग', pg: '49' },
        { eng: 'mandir me kyo kyu sir marati dole', hin: 'मंदीर में क्यो सिर मारती डोले', dir: 'ntn', id: '49.2', bk: 'नाना तिरीचा नामरंग', pg: '49' },
        { eng: 'tin shire saha hath', hin: 'तिन शिरे सहा हात ', dir: 'ntn', id: '51', bk: 'नाना तिरीचा नामरंग', pg: '51' },
        { eng: 'naman maze gururaya', hin: 'नमन माझे गुरुराया', dir: 'ntn', id: '51.2', bk: 'नाना तिरीचा नामरंग', pg: '51' },
        { eng: 'ata kothe dhave mana', hin: 'आता कोठे धावे मना', dir: 'ntn', id: '52', bk: 'नाना तिरीचा नामरंग', pg: '52' },
        { eng: 'avade he rup gojire sagun', hin: 'आवडे हे रुप गोजिरे सगुण', dir: 'ntn', id: '52.2', bk: 'नाना तिरीचा नामरंग', pg: '52' },
        { eng: 'rupi guntale lochan', hin: 'रुपी गुंतले लोचन', dir: 'ntn', id: '52.3', bk: 'नाना तिरीचा नामरंग', pg: '52' },
        { eng: 'sada maze dola', hin: 'सदा माझे डोळा', dir: 'ntn', id: '53', bk: 'नाना तिरीचा नामरंग', pg: '53' },
        { eng: 'sadguru vachoni sapadena soy', hin: 'सद्गुरु वाचोनी सापडेना सोय', dir: 'ntn', id: '53.2', bk: 'नाना तिरीचा नामरंग', pg: '53' },
        { eng: 'namo adirupa', hin: 'नमो आदीरुपा', dir: 'ntn', id: '55', bk: 'नाना तिरीचा नामरंग', pg: '55' },
        { eng: 'avade he rup', hin: 'आवडे हे रुप', dir: 'ntn', id: '55.3', bk: 'नाना तिरीचा नामरंग', pg: '55' },
        { eng: 'sundar te dhyan', hin: 'सुंदर ते ध्यान', dir: 'ntn', id: '56.2', bk: 'नाना तिरीचा नामरंग', pg: '56' },
        { eng: 'dev maza vithu savala', hin: 'देव माझा विठू सावळा', dir: 'ntn', id: '57', bk: 'नाना तिरीचा नामरंग', pg: '57' },
        { eng: 'namila ganapati mauli sharada', hin: 'नमिला गणपती माऊली शारदा', dir: 'ntn', id: '57.2', bk: 'नाना तिरीचा नामरंग', pg: '57' },
        { eng: 'ghyaniyancha raja', hin: 'ज्ञानियांचा राजा', dir: 'ntn', id: '58', bk: 'नाना तिरीचा नामरंग', pg: '58' },
        { eng: 'jayachiye dvari sonyacha pimpal', hin: 'जयाचिये व्दारी; सोन्याचा पिंपळ ', dir: 'ntn', id: '58.2', bk: 'नाना तिरीचा नामरंग', pg: '58' },
        { eng: 'indrayani kathi', hin: 'इंद्रायणी काठी', dir: 'ntn', id: '58.3', bk: 'नाना तिरीचा नामरंग', pg: '58' },
        { eng: 'guru maza moksha data', hin: 'गुरु माझा मोक्ष दाता ', dir: 'ntn', id: '59', bk: 'नाना तिरीचा नामरंग', pg: '59' },
        { eng: 'avadine bhave harinam ghesi', hin: 'आवडीने भावे हरीनाम घेसी', dir: 'ntn', id: '60.2', bk: 'नाना तिरीचा नामरंग', pg: '60' },
        { eng: 'amrutahuni god nam', hin: 'अमृताहुनी गोड नाम', dir: 'ntn', id: '60.3', bk: 'नाना तिरीचा नामरंग', pg: '60' },
        { eng: 'kare ushir laviyela', hin: 'कारे उशीर लावियेला', dir: 'ntn', id: '65.3', bk: 'नाना तिरीचा नामरंग', pg: '65' },
        { eng: 'thevile anante taisechi rahave', hin: 'ठेविले अनंते तैसेचि रहावे ', dir: 'ntn', id: '66.3', bk: 'नाना तिरीचा नामरंग', pg: '66' },
        { eng: 'devpuja mazi', hin: 'देवपूजा मांझी देवपूजा', dir: 'ntn', id: '69.2', bk: 'नाना तिरीचा नामरंग', pg: '69' },
        { eng: 'devachiye dwari', hin: 'देवाचिये द्वारी' , dir: 'ntn', id: '69.3' , bk: 'नाना तिरीचा नामरंग', pg: '69' },
        { eng: 'kanhopatra dasi bole', hin: 'कान्होपात्रा दासी बोले', dir: 'ntn', id: '70.2', bk: 'नाना तिरीचा नामरंग', pg: '70' },
        { eng: 'he adima he antima', hin: 'हे आदिमा हे अंतिमा', dir: 'ntn', id: '71.2', bk: 'नाना तिरीचा नामरंग', pg: '71' },
        { eng: 'abir gulal udhalit rang', hin: 'अबीर गुलाल उधळीत रंग', dir: 'ntn', id: '72.2', bk: 'नाना तिरीचा नामरंग', pg: '72' },
        { eng: 'deva tuza me sonar', hin: 'देवा तुझा मी सोनार ', dir: 'ntn', id: '73.2', bk: 'नाना तिरीचा नामरंग', pg: '73' },
        { eng: 'anandacha kand guru ha', hin: 'आनंदा कंद गुरु हा', dir: 'ntn', id: '73.3', bk: 'नाना तिरीचा नामरंग', pg: '73' },
        { eng: 'krushnatirichya vasanarya', hin: 'कृष्णातिरीच्या वसणाऱ्या', dir: 'ntn', id: '74', bk: 'नाना तिरीचा नामरंग', pg: '74' },
        { eng: 'sangave kavanya thaya jave', hin: 'सांगावे, कवण्या ठाया जावे?', dir: 'ntn', id: '74.2', bk: 'नाना तिरीचा नामरंग', pg: '74' },
		{ eng: 'koni ninda athava vanda', hin: 'कोणी निंदा अथवा वंदा', dir: 'ntn', id: '61.2', bk: 'नाना तिरीचा नामरंग', pg: '61' },            
		{ eng: 'ale devajichya mana', hin: 'आले देवाजीच्या मना ', dir: 'ntn', id: '61.3', bk: 'नाना तिरीचा नामरंग', pg: '61' },            
		{ eng: 'nako mana guntu mayajali', hin: 'नको नको मना गुंतु मायाजाळी', dir: 'ntn', id: '62', bk: 'नाना तिरीचा नामरंग', pg: '62' },            
		{ eng: 'ye ga vithabai', hin: 'ये ग ये ग विठाबाई ', dir: 'ntn', id: '62.2', bk: 'नाना तिरीचा नामरंग', pg: '62' },            
		{ eng: 'javavari tavavari', hin: 'जववरी ते तववरी', dir: 'ntn', id: '62.3', bk: 'नाना तिरीचा नामरंग', pg: '62' },            
		{ eng: 'dhany aji din sant darshanacha', hin: 'धन्य आजी दिन संत दर्शनाचा', dir: 'ntn', id: '63', bk: 'नाना तिरीचा नामरंग', pg: '63' },            
		{ eng: 'deva tuzi kashi karani', hin: 'देवा तुझी कशी करणी', dir: 'ntn', id: '63.2', bk: 'नाना तिरीचा नामरंग', pg: '63' },            
		{ eng: 'kay sangu deva dnyanobachi khyati', hin: 'काय सांगू देवा ज्ञानोबाची ख्याती', dir: 'ntn', id: '63.3', bk: 'नाना तिरीचा नामरंग', pg: '63' },            
		{ eng: 'samadhi sadhan sanjivan', hin: 'समाधी साधन, संजीवन नाम', dir: 'ntn', id: '63.4', bk: 'नाना तिरीचा नामरंग', pg: '63' },            
		{ eng: 'pandharinatha panduranga', hin: 'पंढरी नाथा पांडुरंगा विठ्ठला', dir: 'ntn', id: '64', bk: 'नाना तिरीचा नामरंग', pg: '64' },            
		{ eng: 'amrutachi fale veli', hin: 'अमृताची फळे, अमृताची वेली', dir: 'ntn', id: '64.2', bk: 'नाना तिरीचा नामरंग', pg: '64' },            
		{ eng: 'jaise vahe ganga taise jyanche man', hin: 'जैसे वाहे गंगा तैसे ज्यांचे मन', dir: 'ntn', id: '64.3', bk: 'नाना तिरीचा नामरंग', pg: '64' },            
		{ eng: 'santane sarita keli', hin: 'संताने सरिता केलो तैश्यापरी', dir: 'ntn', id: '64.4', bk: 'नाना तिरीचा नामरंग', pg: '64' },            
		{ eng: 'kay vanu ata na pure vani', hin: 'काय वानू आता न पुरे ही वाणी', dir: 'ntn', id: '65', bk: 'नाना तिरीचा नामरंग', pg: '65' },            
		{ eng: 'dasacha me das shrihari', hin: 'दासाचा मी दास श्रीहरी', dir: 'ntn', id: '65.2', bk: 'नाना तिरीचा नामरंग', pg: '65' },            
		{ eng: 'apuliya bale nahi bolavit', hin: 'आपुलिया बळे नाही बोलावित', dir: 'ntn', id: '65.4', bk: 'नाना तिरीचा नामरंग', pg: '65' },            
		{ eng: 'deulyatalya deva ya ho utara', hin: 'देऊळातल्या देवा या हो उतरा', dir: 'ntn', id: '66', bk: 'नाना तिरीचा नामरंग', pg: '66' },            
		{ eng: 'deva maze man lage tuze charani', hin: 'देवा माझे मन लागे तुझे चरणी', dir: 'ntn', id: '66.2', bk: 'नाना तिरीचा नामरंग', pg: '66' },            
		{ eng: 'pandharicha vas chandrabhage snan', hin: 'पंढरीचा वास चंद्रभागे स्नान', dir: 'ntn', id: '66.4', bk: 'नाना तिरीचा नामरंग', pg: '66' },            
		{ eng: 'papachi vasana nako dau dola', hin: 'पापाची वासना नको दाऊ डोळा', dir: 'ntn', id: '67', bk: 'नाना तिरीचा नामरंग', pg: '67' },            
		{ eng: 'kanya sasuryasi jaye', hin: 'कन्या सासुऱ्याची जाये', dir: 'ntn', id: '67.2', bk: 'नाना तिरीचा नामरंग', pg: '67' },            
		{ eng: 'yethe ka re ubha shrirama', hin: 'येथे का रे उभा श्रीरामा', dir: 'ntn', id: '67.3', bk: 'नाना तिरीचा नामरंग', pg: '67' },            
		{ eng: 'vithu maza lekurvala', hin: 'विठू माझा लेकुरवाळा', dir: 'ntn', id: '67.4', bk: 'नाना तिरीचा नामरंग', pg: '67' },            
		{ eng: 'dharoniya soi paratale', hin: 'धरोनिया सोई पारतले मन', dir: 'ntn', id: '68', bk: 'नाना तिरीचा नामरंग', pg: '68' },            
		{ eng: 'hari bhajanavin kal', hin: 'हरी भजनाविण काळ', dir: 'ntn', id: '68.2', bk: 'नाना तिरीचा नामरंग', pg: '68' },            
		{ eng: 'avaghachi sansar sukhacha', hin: 'अवघाची संसार सुखाचा', dir: 'ntn', id: '68.3', bk: 'नाना तिरीचा नामरंग', pg: '68' },            
		{ eng: 'amuchi maliyachi jat', hin: 'आमुची माळीयाची जात', dir: 'ntn', id: '69', bk: 'नाना तिरीचा नामरंग', pg: '69' },            
		{ eng: 'nako devraya ant', hin: 'नको देवराया', dir: 'ntn', id: '70', bk: 'नाना तिरीचा नामरंग', pg: '70' },            
		{ eng: 'dharila pandharicha chor', hin: 'धरीला पंढरीचा चोर', dir: 'ntn', id: '70.3', bk: 'नाना तिरीचा नामरंग', pg: '70' },            
		{ eng: 'jan vijan zale', hin: 'जन विजन झाले', dir: 'ntn', id: '71', bk: 'नाना तिरीचा नामरंग', pg: '71' },            
		{ eng: 'ekchu tali chandrabhage', hin: 'एकची टाळी घाली चंद्रभागे', dir: 'ntn', id: '71.4', bk: 'नाना तिरीचा नामरंग', pg: '71' },            
		{ eng: 'chintu dattatreya anusuya tanaya', hin: 'चिंतू दत्तात्रेया, अनुसुयातनया । ', dir: 'ntn', id: '74.3', bk: 'नाना तिरीचा नामरंग', pg: '74' },            
		{ eng: 'shrimad vasudev dhyani', hin: 'श्रीमद्वासुदेव ध्यानी', dir: 'ntn', id: '75', bk: 'नाना तिरीचा नामरंग', pg: '75' },           
		{ eng: 'namo guru vasudeva', hin: 'नमो गुरु वासुदेवां', dir: 'ntn', id: '75.2', bk: 'नाना तिरीचा नामरंग', pg: '75' },  
		{ eng: 'ananya vinanti kari charandvay dhari', hin: 'अनन्य विनंती करी, चरणव्दय धरी', dir: 'ntn', id: '76', bk: 'नाना तिरीचा नामरंग', pg: '76' },                      
		{ eng: 'antari nirmal vachecha rasal', hin: 'अंतरी निर्मळ वाचेचा रसाळ', dir: 'ntn', id: '76.2', bk: 'नाना तिरीचा नामरंग', pg: '76' },            
		{ eng: 'bhajan bina jeevan suna',  hin: ' भजन बिना जीवन सुना' , dir: 'ntn',  id: '77.2',  bk: 'नाना तिरीचा नामरंग',  pg: '77' },
		{ eng: 'is tan dhan ki kaun badaai',  hin: ' इस तन धन की कौन बढाई' , dir: 'ntn',  id: '77.3',  bk: 'नाना तिरीचा नामरंग',  pg: '77' },
		{ eng: 'ramras pee lena mere bhaai',  hin: ' रामरस पी लेना मेरे भाई' , dir: 'ntn',  id: '77',   bk: 'नाना तिरीचा नामरंग',  pg: '77' },
		{ eng: 'kuch lena na dena magan rahena',  hin: ' कुछ लेना न देना मगन रहेना ' , dir: 'ntn',  id: '78.2',  bk: 'नाना तिरीचा नामरंग',  pg: '78' },
		{ eng: 'aavat mori galiyan me giridhari',  hin: ' आवत मोरी गलियन में गिरधारी ' , dir: 'ntn',  id: '78.3',  bk: 'नाना तिरीचा नामरंग',  pg: '78' },
		{ eng: 'ghar aaye mere satgurujii',  hin: ' घर आये मेरे सतगुरुजी ' , dir: 'ntn',  id: '78',   bk: 'नाना तिरीचा नामरंग',  pg: '78' },
		{ eng: 'maine ramratan dhan paayo',  hin: ' मैने रामरतन धन पायो ' , dir: 'ntn',  id: '79.2',  bk: 'नाना तिरीचा नामरंग',  pg: '79' },
		{ eng: 'teri koi na rokan haar magan hoi meera chali',  hin: ' तेरी कोई न रोकण हार मगन होई मीरा चली' , dir: 'ntn',  id: '79.3',  bk: 'नाना तिरीचा नामरंग',  pg: '79' },
		{ eng: 'aali maanhe laage vrindavan niko',  hin: ' आली मान्हे लागे वृन्दावन नीको' , dir: 'ntn',  id: '79',   bk: 'नाना तिरीचा नामरंग',  pg: '79' },
		{ eng: 'mere to giridhar gopal',  hin: ' मेरे तो गिरधर गोपाल' , dir: 'ntn',  id: '80.2',  bk: 'नाना तिरीचा नामरंग',  pg: '80' },
		{ eng: 'chalo man ganga jamuna teer',  hin: ' चलो मन गंगा जमुना तीर' , dir: 'ntn',  id: '80.3',  bk: 'नाना तिरीचा नामरंग',  pg: '80' },
		{ eng: 'narayan jinke hai hriday me',  hin: 'नारायण जिनके है हृदय मे' , dir: 'ntn',  id: '80',   bk: 'नाना तिरीचा नामरंग',  pg: '80' },
		{ eng: 'guruvin kaun batave baat',  hin: ' गुरुवीन कौण बतावे बाट' , dir: 'ntn',  id: '81.2',  bk: 'नाना तिरीचा नामरंग',  pg: '81' },
		{ eng: 'doha - kabira jab ham peda huoo jag hase ham roye',  hin: ' दोहा - कबीरा जब हम पैदा हुओ जग हसे हम रोये ' , dir: 'ntn',  id: '81.3',  bk: 'नाना तिरीचा नामरंग',  pg: '81' },
		{ eng: 'naahin aiso janm baran-bar',  hin: 'नाहिं ऐसो जन्म बारं-बार' , dir: 'ntn',  id: '81',   bk: 'नाना तिरीचा नामरंग',  pg: '81' },
		{ eng: 'baje kisanki paijaniya',  hin: ' बाजे किसनकी पैजनिया ' , dir: 'ntn',  id: '82.2',  bk: 'नाना तिरीचा नामरंग',  pg: '82' },
		{ eng: 'radha pyari da daalo bansi hamari',  hin: ' राधा प्यारी द डालो बंसी हमारी ' , dir: 'ntn',  id: '82.3',  bk: 'नाना तिरीचा नामरंग',  pg: '82' },
		{ eng: 'maili chadar odhke kaise dwaar tumhare aau',  hin: ' मैली चादर ओढके कैसे व्दार तुम्हारे आऊ' , dir: 'ntn',  id: '82.4',  bk: 'नाना तिरीचा नामरंग',  pg: '82' },
		{ eng: 'murliya kaye guman bhari',  hin: ' मुरलीया काये गुमान भरी' , dir: 'ntn',  id: '82',   bk: 'नाना तिरीचा नामरंग',  pg: '82' },
		{ eng: 'ab hau nachyo bahut gopala',  hin: ' अब हौ नाच्यो बहुत गोपाला ' , dir: 'ntn',  id: '83.2',  bk: 'नाना तिरीचा नामरंग',  pg: '83' },
		{ eng: 'tum kahan chhupe bhagwan',  hin: ' तुम कहाँ छुपे भगवान' , dir: 'ntn',  id: '83',   bk: 'नाना तिरीचा नामरंग',  pg: '83' },
		{ eng: 'bhulvile venunade',  hin: ' भुलविले वेणुनादे' , dir: 'ntn',  id: '85.2',  bk: 'नाना तिरीचा नामरंग',  pg: '85' },
		{ eng: 'paniyasi kaisi aata ekali mi jau',  hin: ' पानियासी कैसी आता एकली मी जाऊ ' , dir: 'ntn',  id: '86.2',  bk: 'नाना तिरीचा नामरंग',  pg: '86' },
		{ eng: 'khandyavari kambli',  hin: ' खांद्यावरी कांबळी' , dir: 'ntn',  id: '86.3',  bk: 'नाना तिरीचा नामरंग',  pg: '86' },
		{ eng: 'kashi jau mi vrindavana',  hin: ' कशी जाऊ मी वृंदावना' , dir: 'ntn',  id: '86',   bk: 'नाना तिरीचा नामरंग',  pg: '86' },
		{ eng: 'nako vaajavu re kanhoba murli',  hin: ' नको वाजवू रे कान्होबा मुरली ' , dir: 'ntn',  id: '87.2',  bk: 'नाना तिरीचा नामरंग',  pg: '87' },
		{ eng: 'radhe tula pushito ghongadivala',  hin: 'राधे तुला पुशितो घोंगडीवाला ',  dir: 'ntn',  id: '87.3',  bk: 'नाना तिरीचा नामरंग',  pg: '87'},
		{ eng: 'khel khele hari kunjavani',  hin: 'खेळ खेळे हरी कुंजवनी ',  dir: 'ntn',  id: '87',   bk: 'नाना तिरीचा नामरंग',  pg: '87'},
		{ eng: 'daava nayani yashodecha sukumar',  hin: 'दावा नयनी यशोदेचा सुकुमार',  dir: 'ntn',  id: '88.2',  bk: 'नाना तिरीचा नामरंग',  pg: '88'},
		{ eng: 'putalya doralam sakhlya painjan',  hin: 'पुतळ्या डोरलं साखळ्या पैंजण',  dir: 'ntn',  id: '88.3',  bk: 'नाना तिरीचा नामरंग',  pg: '88'},
		{ eng: 'na kale g bai',  hin: 'ना कळे ग बाई',  dir: 'ntn',  id: '88',   bk: 'नाना तिरीचा नामरंग',  pg: '88'},
		{ eng: 'govinda re gopala re',  hin: 'गोविंदा रे गोपाळा रे',  dir: 'ntn',  id: '89.2',  bk: 'नाना तिरीचा नामरंग',  pg: '89'},
		{ eng: 'radte maze bal tanhe',  hin: 'रडते माझे बाळ तान्हे ',  dir: 'ntn',  id: '89',   bk: 'नाना तिरीचा नामरंग',  pg: '89'},
		{ eng: 'paha ge paha',  hin: 'पहा गे पहा',  dir: 'ntn',  id: '90.2',  bk: 'नाना तिरीचा नामरंग',  pg: ''},
		{ eng: 'tuzhi re sangati nahi kamachi',  hin: 'तुझी रे संगती नाही कामाची',  dir: 'ntn',  id: '90',   bk: 'नाना तिरीचा नामरंग',  pg: '90'},
		{ eng: 'gaulan sange gaulanila',  hin: 'गौळण सांगे गौळणीला ',  dir: 'ntn',  id: '91.2',  bk: 'नाना तिरीचा नामरंग',  pg: '91'},
		{ eng: 'gopalkrishna bhagwan vajavi murli',  hin: 'गोपाळकृष्ण भगवान वाजवी मुरली',  dir: 'ntn',  id: '91.3',  bk: 'नाना तिरीचा नामरंग',  pg: '91'},
		{ eng: 'jara thamb ki re kanha yete maghari',  hin: 'जरा थांब की रे कान्हा येते माघारी',  dir: 'ntn',  id: '91',   bk: 'नाना तिरीचा नामरंग',  pg: '91'},
		{ eng: 'dehudya charani dajavito venu',  hin: 'देहुड्या चरणी दाजवितो वेणु',  dir: 'ntn',  id: '92.2',  bk: 'नाना तिरीचा नामरंग',  pg: '92'},
		{ eng: 'tu thamala le thamala apulya gai amhi apulya',  hin: 'तु थमाल ले थमाल आपुल्या गाई आम्ही आपुल्या',  dir: 'ntn',  id: '92',   bk: 'नाना तिरीचा नामरंग',  pg: '92'},
		{ eng: 'kanha mohe na chhedo chhedona',  hin: 'कान्हा मोहे ना छेडो छेडोना',  dir: 'ntn',  id: '93.2',  bk: 'नाना तिरीचा नामरंग',  pg: '93'},
		{ eng: 'ratra kali ghagar kali',  hin: 'रात्र काळी घागर काळी ',  dir: 'ntn',  id: '93.3',  bk: 'नाना तिरीचा नामरंग',  pg: '93'},
		{ eng: 'prit tuzhi bavari hari hari',  hin: 'प्रित तुझी बावरी हरी हरी',  dir: 'ntn',  id: '93',   bk: 'नाना तिरीचा नामरंग',  pg: '93'},
		{ eng: 'vrindavani venu',  hin: 'वृंदावनी वेणु',  dir: 'ntn',  id: '94',   bk: 'नाना तिरीचा नामरंग',  pg: '94'},
		{ eng: 'edka madan',  hin: 'एडका मदन',  dir: 'ntn',  id: '96.2',  bk: 'नाना तिरीचा नामरंग',  pg: '96'},
		{ eng: 'mala dadala nako g bai',  hin: 'मला दादला नको ग बाई',  dir: 'ntn',  id: '96.3',  bk: 'नाना तिरीचा नामरंग',  pg: '96'},
		{ eng: 'surya ugavla prakash padla adva dongar',  hin: 'सुर्य उगवला प्रकाश पडला आडवा डोंगर',  dir: 'ntn',  id: '96',   bk: 'नाना तिरीचा नामरंग',  pg: '96'},
		{ eng: 'sagun gun maya',  hin: 'सगुण गुण माया',  dir: 'ntn',  id: '97.2',  bk: 'नाना तिरीचा नामरंग',  pg: '97'},
		{ eng: 'amhi latike na bolu vartaman khote',  hin: 'आम्ही लटिके न बोलू वर्तमान खोटे ',  dir: 'ntn',  id: '97',   bk: 'नाना तिरीचा नामरंग',  pg: '97'},
		{ eng: 'tumha sangte vegale nidha',  hin: 'तुम्हा सांगते वेगळे निधा',  dir: 'ntn',  id: '98.2',  bk: 'नाना तिरीचा नामरंग',  pg: '98'},
		{ eng: 'vichu chavla',  hin: 'विचू चावला',  dir: 'ntn',  id: '98',   bk: 'नाना तिरीचा नामरंग',  pg: '98'},
		{ eng: 'bai mi bholi vo bai mi bholi',  hin: 'बाई मी भोळी वो बाई मी भोळी',  dir: 'ntn',  id: '99',   bk: 'नाना तिरीचा नामरंग',  pg: '99'},
		{ eng: 'mi vasudev name fodita nitya taho',  hin: 'मी वासुदेव नामे फोडितां नित्य टाहो',  dir: 'ntn',  id: '100',   bk: 'नाना तिरीचा नामरंग',  pg: '100'},
		{ eng: 'aicha jogwa jogwa mi magen',  hin: 'आईचा जोगवा जोगवा मी मागेन ',  dir: 'ntn',  id: '101.2',  bk: 'नाना तिरीचा नामरंग',  pg: '101'},
		{ eng: 'panchbhutacha dehpot ha trigunagune valila',  hin: 'पंचभुतांचा देहपोत हा त्रिगुणगुणे वाळीला ',  dir: 'ntn',  id: '101',   bk: 'नाना तिरीचा नामरंग',  pg: '101'},
		{ eng: 'kanadine kela',  hin: 'कानडीने केला',  dir: 'ntn',  id: '102',   bk: 'नाना तिरीचा नामरंग',  pg: '102'},
		{ eng: 'hari naam visarle',  hin: 'हरी नाम विसरले ',  dir: 'ntn',  id: '103.2',  bk: 'नाना तिरीचा नामरंग',  pg: '103'},
		{ eng: 'gav vasad padu naka',  hin: 'गाव वसाड पाडू नका',  dir: 'ntn',  id: '103',   bk: 'नाना तिरीचा नामरंग',  pg: '103'},
		{ eng: 'nijalis kay ge',  hin: 'निजलीस काय गे ',  dir: 'ntn',  id: '104.2',  bk: 'नाना तिरीचा नामरंग',  pg: '104'},
		{ eng: 'amhi gondhali gondhali',  hin: 'आम्ही गोंधळी गोंधळी',  dir: 'ntn',  id: '104',   bk: 'नाना तिरीचा नामरंग',  pg: '104'},
		{ eng: 'bhoot jabar mothe g bai',  hin: 'भूत जबर मोठे ग बाई',  dir: 'ntn',  id: '105.2',  bk: 'नाना तिरीचा नामरंग',  pg: '105'},
		{ eng: 'satvar paav g mala',  hin: 'सत्वर पाव ग मला',  dir: 'ntn',  id: '105',   bk: 'नाना तिरीचा नामरंग',  pg: '105'},
		{ eng: 'ashi kashi gant gadi gadyaano',  hin: 'अशी कशी गंमत झाली गड्यांनो',  dir: 'ntn',  id: '106.2',  bk: 'नाना तिरीचा नामरंग',  pg: '106'},
		{ eng: 'bai mi kashi',  hin: 'बाई मी कशी',  dir: 'ntn',  id: '106',   bk: 'नाना तिरीचा नामरंग',  pg: '106'},
		{ eng: 'muka mi jalo vacha geli',  hin: 'मुका मी झालो वाचा गेली ',  dir: 'ntn',  id: '107.2',  bk: 'नाना तिरीचा नामरंग',  pg: '107'},
		{ eng: 'katyanchya anivar vasti teen gav',  hin: 'काट्यांच्या अणिवर वसती तीन गाव',  dir: 'ntn',  id: '108',   bk: 'नाना तिरीचा नामरंग',  pg: '108'},
		{ eng: 'vahava sahebji',  hin: 'वाहवा साहेबजी ',  dir: 'ntn',  id: '109.2',  bk: 'नाना तिरीचा नामरंग',  pg: '109'},
		{ eng: 'tumhi vasudev vasudev mhana',  hin: 'तुम्ही वासुदेव वासुदेव म्हणा ',  dir: 'ntn',  id: '109',   bk: 'नाना तिरीचा नामरंग',  pg: '109'},
		{ eng: 'mi bhatin ale re bhata',  hin: 'मी भटीण आले रे भटा ',  dir: 'ntn',  id: '110',   bk: 'नाना तिरीचा नामरंग',  pg: '110'},
		{ eng: 'kiti karava dhava',  hin: 'किती करावा धावा',  dir: 'ntn',  id: '111.2',  bk: 'नाना तिरीचा नामरंग',  pg: '111'},
		{ eng: 'shruguru charani janchi preeti',  hin: 'श्रीगुरु चरणी ज्यांची प्रीती ',  dir: 'ntn',  id: '111',   bk: 'नाना तिरीचा नामरंग',  pg: '111'},
		{ eng: 'induras jave',  hin: 'इंदुरास जावे',  dir: 'ntn',  id: '112.2',  bk: 'नाना तिरीचा नामरंग',  pg: '112'},
		{ eng: 'naval aikile mi aaj',  hin: 'नवल ऐकिले मी आज',  dir: 'ntn',  id: '112',   bk: 'नाना तिरीचा नामरंग',  pg: '112'},
		{ eng: 'paha ho raja induracha',  hin: 'पहा हो राजा इंदूरचा ',  dir: 'ntn',  id: '113.2',  bk: 'नाना तिरीचा नामरंग',  pg: '113'},
		{ eng: 'kiti bhaktanche door kari kasht ho',  hin: 'किती भक्तांचे दूर करी कष्ट हो.',  dir: 'ntn',  id: '113',   bk: 'नाना तिरीचा नामरंग',  pg: '113'},
		{ eng: 'jithe thakli vedapurane',  hin: 'जिथे थकली वेदपुराणे',  dir: 'ntn',  id: '114.2',  bk: 'नाना तिरीचा नामरंग',  pg: ''},
		{ eng: 'man mandiri ya ho nana',  hin: 'मन मंदिरी या हो नाना',  dir: 'ntn',  id: '114',   bk: 'नाना तिरीचा नामरंग',  pg: '114'},
		{ eng: 'darbara madhi alo amhi namaskar',  hin: 'दरबारा मधी आलो आम्ही नमस्कार',  dir: 'ntn',  id: '115.2',  bk: 'नाना तिरीचा नामरंग',  pg: '115'},
		{ eng: 'datt digambar',  hin: 'दत्त दिगंबर',  dir: 'ntn',  id: '115',   bk: 'नाना तिरीचा नामरंग',  pg: '115'},
		{ eng: 'amhi nananche gondhali',  hin: 'आम्ही नानांचे गोंधळी',  dir: 'ntn',  id: '116',   bk: 'नाना तिरीचा नामरंग',  pg: '116'},
		{ eng: 'apne bhakton ko kya se kya bana dete hain',  hin: 'अपने भक्तों को क्या से क्या बना देते हैं',  dir: 'ntn',  id: '117',   bk: 'नाना तिरीचा नामरंग',  pg: '117'},
		{ eng: 'nana tere darpe ek',  hin: 'नाना तेरे दरपे एक',  dir: 'ntn',  id: '118',   bk: 'नाना तिरीचा नामरंग',  pg: '118'},
		{ eng: 'gaon indur indoor indore', hin: 'गांव इंदूर', dir: 'ntn', id: '119' , bk: 'नाना तिरीचा नामरंग', pg: '119' }, 
		{ eng: 'arati karpur kapur', hin: 'कर्पूर आरती', dir: 'ntn', id: '120' , bk: 'नाना तिरीचा नामरंग', pg: '120' }, 
		{ eng: 'hechi dan', hin: 'हेचि दान देगा देवा', dir: 'ntn', id: '121.2' , bk: 'नाना तिरीचा नामरंग', pg: '' }, 
		{ eng: 'krupalu kripalu sajjan tumhi santjan', hin: 'कृपाळू सज्जन तुम्ही संतजन', dir: 'ntn', id: '121', bk: 'नाना तिरीचा नामरंग', pg: '121' },
		{ eng: 'akalp ayushya vhave', hin: 'आकल्प आयुष्य व्हावे', dir: 'ntn', id: '123.2' , bk: 'नाना तिरीचा नामरंग', pg: '123' }, 
		{ eng: 'hechi vhavi mazi aas', hin: 'हेचि व्हावी माझी आस ', dir: 'ntn', id: '123' , bk: 'नाना तिरीचा नामरंग', pg: '123' }, 
		{ eng: 'shevatachi vinavani', hin: 'शेविटची विनवणी ', dir: 'ntn', id: '124.2' , bk: 'नाना तिरीचा नामरंग', pg: '124' }, 
		{ eng: 'magane he ek tuzprati ahe', hin: 'मागणे हे एक तुजप्रती आहे', dir: 'ntn', id: '124', bk: 'नाना तिरीचा नामरंग', pg: '124' },
		{ eng: 'sada sarvada yon', hin: 'सदा सर्वदा योग ', dir: 'ntn', id: '125' , bk: 'नाना तिरीचा नामरंग', pg: '125' }, 
		{ eng: 'vandu gurunchya charanarvinda', hin: 'वंदू गुरुच्या चरणार विंदा', dir: 'ntn', id: '126' , bk: 'नाना तिरीचा नामरंग', pg: '126' }, 









// { eng: '', hin: '', dir: 'ntn', id: '', bk: 'नाना तिरीचा नामरंग', pg: '' },            



    ];

if (typeof module === 'object' && module.exports) {
    module.exports = ntn;
}
