name: Update Index B1, Index Data, and SQLite DB

on:
  push:
    branches:
      - main
    paths:
      - "bhajans/b1/*.txt"

jobs:
  update-everything:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: pip install indic-transliteration json5

      - name: Run update script
        run: python update_b1.py

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node dependencies
        run: npm install

      - name: Update index-data file
        run: node ./scripts/indexgenerator.js

      - name: Rebuild SQLite database
        run: npm run build-db

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add scripts/b1.js scripts/indexdata.js db/bhajans.sqlite

          if ! git diff --cached --quiet; then
            git commit -m "Update b1.js, indexdata.js, and SQLite DB"
            git push
          else
            echo "No changes to commit"
          fi
