name: Update Index B1 and Index Data

on:
  push:
    branches:
      - main
    paths:
      - "bhajans/b1/*.txt"

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install indic-transliteration json5

      - name: Run update script
        run: python update_b1.py

      - name: Update b1.js file with new entries
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/b1.js
          git commit -m "Update b1.js with new entries" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

  update-file:
    runs-on: ubuntu-latest
    needs: update-index   # runs after the first job finishes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts

      - name: Update index-data file with new entries
        run: node ./scripts/indexgenerator.js

      - name: Commit indexdata.js changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull --rebase origin main
          git add ./scripts/indexdata.js
          git commit -m "Update file with new index data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
