name: Update Index B1

on:
  push:
    paths:
      - "bhajans/b1/*.txt"   # trigger only when new text files are added

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install indic-transliteration
          pip install json5

      - name: Run update script
        run: python update_b1.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/b1.js
          git commit -m "Update b1.js with new entries" || echo "No changes to commit"
          git push
